### PR TITLE
Parquet

### PR DESCRIPTION
**Pull request by kalyancv**

### CODE REVIEW

**Comment by kalyancv** [comment]
Parquet

**Comment by sahilTakiar** [comment]
Hey @kalyancv it seems that there are a few unnecessary binary files in your Pull Request. Could you remove them? Specifically referring to the ones under `gobblin-rest-service`.

Also, the new classes you have written are under `gobblin-example`, can you move them to `gobblin-core`?

**Comment by prashantbh** [comment]
Hey @sahilTakiar, I am doing these changes. Once this code is bug free and running correctly I'll move it to gobbline-core and raise a pull request. I'll also need someone to do code review.

**Comment by liyinan926** [comment]
@kalyancv Gobblin uses the coding style outlined here https://github.com/linkedin/gobblin/wiki/CodingStyle. Please make sure your code follows the coding style. Please also get rid of files such as `.Ds_Store` and all the generated Java classes.

**Comment by sahilTakiar** [comment]
@kalyancv any update on this?

**Comment by kalyancv** [comment]
Hi Sahil,prashantbh working on this. our company wants to use flume, due to going with cloudera.
Thanks & RgdS
Kalyan

**Comment by sahilTakiar** [comment]
@prashantbh any update on this?

**Comment by sahilTakiar** [comment]
@prashantbh closing due to inactivity, please re-open if needed

**Pull request closed without merging**
