### PR TITLE
Support for publishing libraries to mavenLocal

### PR DESCRIPTION
**Pull request by kadaan**
Fix for #542 and #545

### CODE REVIEW

**Comment by chavdar** [comment]
Hey, thanks for catching this. It looks like we've missed the following section from the Pegasus doc: https://github.com/linkedin/rest.li/wiki/Gradle-build-integration#publishing-maven-artifacts . It looks similar to yours. What do you think about adding the "official" documentation?

**Comment by kadaan** [comment]
I tried adding that last night and while it meant the data-template jar was uploaded to artifactory, the empty jar was still there.  The layout would then be:

 gobblin-rest-api-VERSION.jar 				261 bytes
 gobblin-rest-api-VERSION-sources.jar 			261 bytes
 gobblin-rest-api-VERSION-javadoc.jar 			261 bytes
 gobblin-rest-api-VERSION-data-template.jar 	41 kilobytes

I’m not confident that this would actually solve the problem.  In addition, it seems misleading that the jar, sources.jar and javadoc.jar are empty.

**Comment by kadaan** [comment]
The build failure should be fixed by #548

**Comment by chavdar** [comment]
@kadaan can you have a look at https://github.com/linkedin/gobblin/pull/550 ? This generates two more artifacts gobblin-rest-api-data-template and gobblin-rest-api-rest-client . gobblin-rest-api.jar is empty because there is no code in src/main/java . The concern that I have about your PR is that if someone adds code under src/main/java , it will be dropped since gobblin-rest-api.jar gets overwritten.

**Pull request closed without merging**
