### PR TITLE
Optimize tasks with only one branch by removing the need for an intermediary queue.

### PR DESCRIPTION
**Pull request by kadaan**
@sahilTakiar Can you get this to the right person for review?

### CODE REVIEW

**Comment by sahilTakiar** [comment]
@shirshanka @chavdar does someone have time to review this? I think we should consider removing the intermediate queue all together. It makes the logic complex and can lead to race conditions (e.g. #840). Unless others have seen concrete scenarios where it makes a performance difference? Last I remember I hadn't seen any such cases.

**Comment by kadaan** [comment]
I think it "could" help when there are multiple forks if each fork pulls independently. That said, I'm not sure how many forks are needed to see a perfect gain over SyncFork.

**Comment by kadaan** [comment]
BTW, you can now run JMH benchmarks via `./gradlew jmh`

**Comment by kadaan** [comment]
I believe failing test is due to the shutdown taking slightly longer than the given 1s.  The streaming code has a 1s timeout on the poll loop and when shutdown is called that time + time for the stack to unwind end up being longer than the test waits.  To quote gitter:

> Joel Baranick @kadaan Jan 20 10:27
> I changed to code in that test to:
> long startTime = System.currentTimeMillis();
> boolean success = task.awaitShutdown(10000);
> Assert.assertTrue(success, "Task should shutdown in 10 seconds");
> log.info("Task done waiting to shutdown {} after {}ms", success, System.currentTimeMillis() - startTime);
> what I see in the logs is: 2017-01-20 10:26:44 PST INFO [main] gobblin.runtime.TaskContinuousTest 223 - Task done waiting to shutdown true after 1007ms
> So it likely fails due to taking slightly longer than the 1s requested.
> Am I correct that the assumption that the task will shutdown in 1s is because of this in Task: long commitIntervalMillis = 1000; // TODO: Configure
> 
> Joel Baranick @kadaan Jan 20 10:35
> Also, is there a reason we need to verify that it shuts down in 1s?
> 
> Joel Baranick @kadaan Jan 20 10:46
> What about asserting a longer shutdown time, but verifying that the Task pulled at most one more record after being told to shutdown.
>  long indexBeforeShutdown = continuousExtractor.index;
> task.shutdown();
> long shutdownStartTime = System.currentTimeMillis();
> log.info("Shutting down task now");
> boolean success = task.awaitShutdown(10000);
> long shutdownEndTime = System.currentTimeMillis();
> long indexAfterShutdown = continuousExtractor.index;
> Assert.assertTrue(success, "Task should shutdown in 10 seconds");
> Assert.assertTrue(indexAfterShutdown - indexBeforeShutdown <= 1, "Task should have pulled at most one more record after calling shutdown");
> log.info("Task done waiting to shutdown {} after {}ms", success, shutdownEndTime - shutdownStartTime);
> 
> Shirshanka Das @shirshanka Jan 20 12:00
> hmm… ok I think I know what might be going on
> in the case of an orderly shutdown.. I was sending down a shutdown record
> and the fork was using that to shut itself down quickly
> it is possible that your change for sync fork / async fork might have changed that behavior slightly
> I haven’t looked at your PR yet… let me see what happens in the Task.shutdown code path now
> 
> Joel Baranick @kadaan Jan 20 12:37
> It is possible that it has changed, but from my understanding the async fork should perform exactly like the previous code. If that is not that case, it is a bug.
> If feels to me that the 1s time limit is too tight, as the streaming code blocks for a second while reading, right?
> That would explain why it was shutting down in 1007ms.
> Like:
> 2017-01-20 10:48:13 PST INFO  [main] gobblin.runtime.TaskContinuousTest 227 - Task done waiting to shutdown true after 1008ms
> 
> Shirshanka Das @shirshanka Jan 20 15:37
> ok, let me check whether the master build also fails intermittently due to this

**Comment by kadaan** [comment]
@shirshanka Ping

**Pull request merged**
