### PR TITLE
Support for generating Idea projects with the correct language level,…

### PR DESCRIPTION
**Pull request by kadaan**
… annotation processors enabled, and a dependencies needed to run the example.

### CODE REVIEW

**Comment by chavdar** [comment]
@ibuenros  or @liyinan926 could you review since you use IDEA.

**Comment by chavdar** [comment]
@kadaan the build fails in JDK 7. Does the org.inferred.processors plugin require JDK 8 ?

**Comment by kadaan** [comment]
@chavdar You are right, it does require JDK8 (for no reason other than being built for that JDK).  I've forked it as info.kadaan.processors, built is for JDK7, and pushed it to the gradle plugin repository.  I tested it against the gradle build locally with a command like: ./gradlew idea -PuseHadoop2 -PhadoopVersion=2.6.0 -Dorg.gradle.java.home=/Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home

**Comment by ibuenros** [comment]
LGTM

**Comment by kadaan** [comment]
Can this be merged?

**Comment by liyinan926** [comment]
I'm not quite comfortable with a forked copy of `org.inferred.processors`.

**Comment by kadaan** [comment]
@liyinan926 What would you suggest then?

**Comment by kadaan** [comment]
@liyinan926 The PR to org.inferred.processors has been accepted and a new version of the plugin has been released.  I've updated this PR to use the new version.

**Comment by liyinan926** [comment]
@kadaan sounds great! Thanks for the update!

**Comment by liyinan926** [comment]
LGTM. Will merge soon.

**Comment by kadaan** [comment]
Yay!!!

**Pull request merged**
