### PR TITLE
Initial commit for gobblin-cluster; gobblin-yarn refactoring

### PR DESCRIPTION
**Pull request by sahilTakiar**
Initial commit for a new sub-module called `gobblin-cluster`

* `gobblin-cluster` provides clustering abilities independent of `gobblin-yarn`
* `gobblin-cluster` essentially just uses Helix for its clustering abilities, and leaves the task of resource management to an external system (e.g. YARN, Mesos, or a CLI)
* This PR is just a refactoring of `gobblin-yarn`, there is no new additional logic, only refactoring
* `gobblin-yarn` already has all the integration with Helix necessary for an initial version of `gobblin-cluster` to work
* More features can be added on top of this, but all the required code to get a basic Gobblin Cluster up and running is now present in `gobblin-cluster`
* This PR basically takes all the Helix logic in `gobblin-yarn` and puts it into `gobblin-cluster`; `gobblin-cluster` has no YARN dependencies

* Most classes have simply been renamed, and their package name changes; but there are few classes that were split into multiple classes:
    * A portion of `GobblinYarnConfigurationKeys` was split into `GobblinClusterConfigurationKeys`
    * Most of the logic in `GobblinApplicationMaster` was moved into `GobblinClusterManager`
        * `GobblinApplicationMaster` now only runs the YARN specific services:
            * `YarnService`
            * `YarnContainerSecurityManager`
            * `GobblinYarnLogSource`
        * `GobblinApplicationMaster` now `extends` `GobblinClusterManager`
    * A portion of `GobblinYarnMetricTagNames` was split into `GobblinClusterMetricTagNames`
    * A portion of `YarnHelixUtils` was split into `GobblinClusterUtils`
    * A portion of `gobblin.yarn.HelixMessageSubTypes` was split into `gobblin.cluster.HelixMessageSubTypes`
    * Most of the logic in `GobblinWorkUnitRunner` was moved into `GobblinTaskRunner`
        * `GobblinWorkUnitRunner` was renamed to `GobblinYarnTaskRunner`
        * `GobblinYarnTaskRunner` now extends `GobblinTaskRunner`

Tests:
* `GobblinApplicationMasterTest` was moved into `gobblin-cluster`
    * It was renamed to `GobblinClusterManagerTest`
* `GobblinHelixJobLauncherTest` was moved into `gobblin-cluster`
* `GobblinHelixTaskTest` was moved into `gobblin-cluster`
* `GobblinWorkUnitRunnerTest` was moved into `gobblin-cluster`
    * It was renamed to `GobblinTaskRunnerTest`
* `JobConfigurationManagerTest` was moved into `gobblin-cluster`

All other changes are simply re-factoring of logic to accommodate the above changes.

* Other changes:
    * Added the `Alpha` tag to all classes in `gobblin-cluster`
    * Added `CLUSTER` to the enum `JobLauncherType` in `JobExecutionInfo.pdsc`

While this PR provides the basis for running Gobblin independent from any resource manager, there are certain features that are still missing:
* Launch scripts for `GobblinClusterManager` and `GobblinTaskRunner`
* A solid log aggregation story; `gobblin-yarn` has `GobblinYarnLogSource` but this class depends on the existence of a distributed file system to do log aggregation
* A global application id - `gobblin-yarn` derives its application id from the application master id, but `gobblin-cluster` has no such concept; currently the application is hardcoded to `1`

### CODE REVIEW

**Comment by abti** [comment]
@sahilTakiar Does this derives from the gobblin-cluster on which me and @shirshanka were working ( https://github.com/abti/gobblin/tree/gobblin_cluster ) or is it independent of it?

**Comment by sahilTakiar** [comment]
@abti wasn't aware you guys were working on that. Is the following link show an accurate diff of the work that has been done: https://github.com/linkedin/gobblin/compare/master...abti:gobblin_cluster?expand=1

If it is, then there shouldn't be any conflict. This PR is just re-factoring, there is no logic change. What are the goals of the work you and Shirshanka have been working on? With this PR, there will be a supported way of spinning up a series of process across multiple machines that can all execute Gobblin Tasks. It's basically `gobblin-yarn` without the container management.

**Comment by abti** [comment]
@sahilTakiar no, that (diff link) does not reflect the whole work. we have certain commits not on gobblin-cluster branch (abti fork) .. but on dev_abti and dev_sdas and locally .. 

the work we are doing is something similar.. ie fork out cluster management out of gobblin-yarn so that we can provision and run gobblin on any cluster management system (yarn / mesos / standalone cluster or  aws)

however lets do this.. first review your changes and merge them in, and then I will merge your changes in my fork manually and then include whatever we have done so far and create a PR for that

**Comment by sahilTakiar** [comment]
@abti I can't seem to find the changes you are referring to under `dev_abti` or `dev_sdas`, could you provide me a link to the diff?

**Comment by abti** [comment]
@sahilTakiar those are not checked in. @shirshanka mostly wrote the abstractions, he can share that. I have provisioner and basic abstraction which I can check in after clean up and merge later as discussed

**Comment by sahilTakiar** [comment]
@abti @zliu41 can you review?

@chavdar you may be interested in this too, a detailed explanation of this PR is in the PR description.

**Comment by abti** [comment]
I went through the PR, and I only have a couple of feedbacks:
- we should add gobblin-cluster specific test cases, and
- we should have a gobblin-cluster launch script (that essentially takes a list of static nodes / ips and launches Gobblin on them) 

I will try to add those along with subsequent PRs around gobblin-cluster 

Note: Merging in the PR since its mostly refactoring and I tested the resultant code base on internal LinkedIn Yarn clusters and it works fine

**Pull request merged**
