### PR TITLE
Support credential encryption for ADL as a source

### PR DESCRIPTION
**Pull request by jinhyukchang**
Integration test passed.

pull file snippet:
...
source.filebased.fs.uri=adl://[REDACTED].azuredatalakestore.net/
source.filebased.encrypted.dfs.adls.oauth2.credential=ENC(REDACTED)
encrypt.key.loc=/path/to/crypto.key
dfs.adls.oauth2.refresh.url=https://login.microsoftonline.com/REDACTED/oauth2/token
dfs.adls.oauth2.client.id=REDACTED

...

### CODE REVIEW

**Comment by jinhyukchang** [comment]
@ibuenros Could you take a look when you have a chance? Thanks!

**Comment by ibuenros** [comment]
@jinhyukchang I don't quite understand what this PR is achieving. Can you give me a short explanation?

**Comment by jinhyukchang** [comment]
@ibuenros I think the PR subject is misleading and actually the PR is to support credential encryption for ADL as a source using HadoopUtil by passing config prefix that is encrypted. (It's same approach as what's done when it writes to ADL)

https://github.com/linkedin/gobblin/blob/master/gobblin-utility/src/main/java/gobblin/util/HadoopUtils.java#L685

**Comment by jinhyukchang** [comment]
@ibuenros Please let me know if you have any doubt. Thanks!

**Pull request merged**
