### PR TITLE
S3 support.

### PR DESCRIPTION
**Pull request by rayortigas**

### CODE REVIEW

**Comment by lqiao** [comment]
We need to make access to S3 optionally via a proxy? That's how we deploy on internal hadoop cluster.

**Comment by rayortigas** [comment]
I think this can be done by configuring jets3t properties (which Hadoop S3 FS uses internally). Look for the various httpclient.proxy* keys:

http://jets3t.s3.amazonaws.com/toolkit/configuration.html#jets3t

I'll research this and comment back.

**Comment by rayortigas** [comment]
If you add a file `conf/jets3t.properties` (relative to the Gobblin home directory) like below, Gobblin will use the specified proxy to connect to S3.

```ini
httpclient.proxy-autodetect=false
httpclient.proxy-host=<host>
httpclient.proxy-port=<port>
```

**Comment by sahilTakiar** [comment]
Thanks for doing the research @rayortigas, this LGTM also. Based on the code and a little more research looks like connections to S3 from a Hadoop gateway can be done as follows:

1: Set the appropriate S3 environment variables that contain the credentials for connecting to S3
2: Add credentials to the core-site.xml file of the Hadoop cluster: https://wiki.apache.org/hadoop/AmazonS3

This pull request adds functionality to allow for option 1. If the env variables are present, they will be set in the Hadoop fs connection.

If there are no other comments, I can go ahead and do the Merge.

**Comment by rayortigas** [comment]
Hi @sahilTakiar,

The intent was to support option 1 but I think this will also cover option 2, in case the env vars are not set.

If I understand https://github.com/apache/hadoop/blob/trunk/hadoop-common-project/hadoop-common/src/main/java/org/apache/hadoop/conf/Configuration.java#L678 correctly, the no-args `Configuration` constructor will pull default settings from `core-site.xml`.

Thanks,
Ray

**Comment by rayortigas** [comment]
I now realize that this is basically what you were saying, @sahilTakiar. :)

**Comment by rayortigas** [comment]
So, you basically had S3 support all along! :D Using env vars is probably more preferable, but the settings in `core-site.xml` would've worked fine.

**Comment by sahilTakiar** [comment]
Merged! Thanks for the contribution and investigation @rayortigas!

**Pull request merged**
