### PR TITLE
Propagate FinalState from RetryWriter and ThrottleWriter

### PR DESCRIPTION
**Pull request by agepati**
Writer bytesWritten and recordsWritten metrics are not being propagated through because DataWriters are now wrapped with RetryWriter, and ThrottleWriter depending on the configuration.

The call hierarchy is now RetryWriter -> [ThrottleWriter ->] DataWriter. Since RetryWriter and ThrottleWriter are not implementing the FinalState interface, Fork.getFinalState is skipping the getFinalState invocation to include the Writer Constructs into the state.

This fix implements FinalState in the RetryWriter and ThrottleWriter to address the issue.

### CODE REVIEW

**Comment by agepati** [comment]
@chavdar, @jinhyukchang Could you please review?

**Comment by jinhyukchang** [comment]
It seems it's following the pattern on how it was done with SpeculativeAttemptAwareConstruct. Code itself looks correct, but I am afraid it would keep fanning out. 
@chavdar Do you think it would make sense to introduce an abstract class to DataWriter that returns defaults?

**Comment by chavdar** [comment]
@jinhyukchang I don't think I understand you comment about fanning out.

**Comment by jinhyukchang** [comment]
@chavdar What I meant was, we would need to add more methods like this change in the future. For that case, how about introducing abstract class (e.g: AbstractDecoratedDataWriter) that provides default behavior? As you can see from this PR change in RetryWriter and ThrottleWriter are the same.

**Comment by chavdar** [comment]
I see that makes sense.

**Comment by agepati** [comment]
@jinhyukchang Wouldn't it make sense to include the number of retryAttempts, or the number of throttleRefused metrics in the respective getFinalState methods?

**Comment by agepati** [comment]
This is to fix https://github.com/linkedin/gobblin/issues/1454

**Comment by agepati** [comment]
@chavdar Could you please review?

**Comment by chavdar** [comment]
@agepati There are test compilation failures

    /home/travis/build/linkedin/gobblin/gobblin-core/src/test/java/gobblin/writer/RetryWriterTest.java:67: error: cannot find symbol
      PartitionedDataWriter writer = mock(PartitionedDataWriter.class, Mockito.CALLS_REAL_METHODS);
                                                                     ^
    symbol:   variable Mockito
    location: class RetryWriterTest
/home/travis/build/linkedin/gobblin/gobblin-core/src/test/java/gobblin/writer/jdbc/JdbcWriterCommandsTest.java:93: warning: JdbcRowSetImpl is internal proprietary API and may be removed in a future release
      return new JdbcRowSetImpl(){
               ^
/home/travis/build/linkedin/gobblin/gobblin-core/src/test/java/gobblin/writer/ThrottleWriterTest.java:84: error: cannot find symbol
      PartitionedDataWriter writer = mock(PartitionedDataWriter.class, Mockito.CALLS_REAL_METHODS);
                                                                     ^
    symbol:   variable Mockito
    location: class ThrottleWriterTest

**Comment by agepati** [comment]
@chavdar There seems to be some classpath issue. Made a change to mock the specific method instead. Could you please review?

**Comment by pcadabam** [comment]
Minor comment. Please use `_instanceVariable` or `this.instanceVariable` instead of `instanceVariable`
LGTM

**Pull request merged**
