### PR TITLE
Refactored some metric names so the naming is more consistent

### PR DESCRIPTION
**Pull request by liyinan926**
Signed-off-by: Yinan Li <liyinan926@gmail.com>

### CODE REVIEW

**Comment by ibuenros** [comment]
Closing the Timer.Context does nothing but record the time. I think ensuring a close does nothing but possibly confuse metrics.

**Comment by liyinan926** [comment]
OK, I didn't realize that. I was just thinking based on the name that it returns a `MetricContext`, which should be properly closed.

**Comment by liyinan926** [comment]
OK, updated.

**Comment by ibuenros** [comment]
LGTM

**Pull request merged**
