### PR TITLE
Removing MRCompactorAvroKeyDedupJobRunnerTest.java

### PR DESCRIPTION
**Pull request by chavdar**
It does not compile and it is not being run

### CODE REVIEW

**Comment by chavdar** [comment]
@ibuenros  can you review?

**Comment by ibuenros** [comment]
Do we have another similar test? If not, could you open an issue/ticket to create a test for this? Otherwise LGTM.

**Comment by chavdar** [comment]
@ibuenros I've reverted the test removal and I've fixed it so it passes now.

**Comment by chavdar** [comment]
@ibuenros any comments?

**Comment by ibuenros** [comment]
LGTM

**Pull request merged**
