### PR TITLE
Support for publishing libraries to mavenLocal

### LINKED ISSUE #542: Cannot publish libraries to mavenLocal
I'm trying to modify gobblin and then test out the changes with an external project that includes additional sources, extractors, etc.  I don't want to publish the libraries to artifactory unless the changes have been accepted back in gobblin trunk.  To deal with this I want to be able to publish the libraries to mavenLocal.  Unfortunately, give then current build.gradle this doesn't seem possible.  I added the following to the build.gradle and was able to publish the libraries to mavenLocal:
```
    install {
      repositories {
        mavenInstaller {
          mavenLocal()
          pom.project {
            name "${project.name}"
            packaging 'jar'
            description 'Gobblin Ingestion Framework'
            url 'https://github.com/linkedin/gobblin/'
          }
        }
      }
    }
```

While this worked fine, there is an issue with the gobblin-rest-api project.  The published library gobblin-rest-api-0.5.0-383-g93635fd contains no code.  It turns out that the code is within a different library `mainDataTemplateJar` which resolves to gobblin-rest-api-data-template-0.5.0-383-g93635fd.jar.  For some reason, when I publish to artifactory the gobblin-rest-api-0.5.0-383-g93635fd.jar contains code.  

I've come up with a work around by adding the following to the gobblin-rest-api build.gradle:
```
artifacts {
    runtime mainDataTemplateJar
    archives mainDataTemplateJar
}

def runtimeJarArtifact
configurations.runtime.artifacts.each {
    if (it.name == "gobblin-rest-api-data-template") {
        it.name = "gobblin-rest-api"
    } else if (it.classifier == "") {
        runtimeJarArtifact = it
    }
}
configurations.runtime.artifacts.remove(runtimeJarArtifact)

def archiveJarArtifact
configurations.archives.artifacts.each {
    if (it.name == "gobblin-rest-api-data-template") {
        it.name = "gobblin-rest-api"
    } else if (it.classifier == "") {
        archiveJarArtifact = it
    }
}
configurations.archives.artifacts.remove(archiveJarArtifact)
```

It feels like this hack should not be needed and I must be doing something wrong.  My gradle-fu is admittedly weak, so any advice on how to get gobblin to properly publish to mavenLocal would be much appreciated.

### PR DESCRIPTION
**Pull request by kadaan**
With this change developers can now publish the gobblin libraries to local maven by running: `./gradlew clean build install`. Fixes #542

### CODE REVIEW

**Comment by kadaan** [comment]
@chavdar: Recreated this PR, removing the fix for #545 that you guys did differently.

**Comment by chavdar** [comment]
LGTM.

By the way, my fix didn't work completely -- we are generating the new artifacts but the dependencies are not captured correctly. We are working with the rest.li team to figure this out.

**Comment by kadaan** [comment]
Well, if a stopgap is needed, my fix did work.  The issue at hand is we can't build against gobblin unless #545 is fixed.

**Comment by kadaan** [comment]
Anything blocking this from being merged?

**Comment by kadaan** [comment]
@chavdar Anything blocking this from being merged?

**Comment by kadaan** [comment]
@chavdar I don't want to pester, but can this be merged?

**Comment by chavdar** [comment]
I am sorry for the delay.

**Comment by kadaan** [comment]
No worries. Thanks for doing all the reviews!!!

**Pull request merged**
