### PR TITLE
Upgrading and re-enabling Findbugs

### PR DESCRIPTION
**Pull request by sahilTakiar**
* Upgraded FindBugs to version 3.0.1 which is compatible with Java 8, this new version only requires Java 7+ to run
* I can't find an option to set a threshold for the number of allowable findbugs bugs before a failure is trigger
    * Unless we find a way to do so, we would have to resolve all findbugs bugs before adding this to the Travis build

@chavdar can you review?

### CODE REVIEW

**Comment by sahilTakiar** [comment]
This should at least allow us and any other users to run findbugs using the following command: `./gradlew findbugsMain`

**Comment by kadaan** [comment]
Can we enable it in travis by default?

**Comment by kadaan** [comment]
Fix for part of #770

**Comment by chavdar** [comment]
@sahilTakiar The threshold is actually part of the hudson plugin. We can check if there is some similar gradle plugin or we can define a gradle task to do that.

**Comment by sahilTakiar** [comment]
@kadaan yes, we should aim to get FindBugs running on Travis, thanks for opening: https://github.com/linkedin/gobblin/issues/770

@chavdar yes I tried to find a similar functionality in Gradle, but couldn't find much. The default config options for the findbugs plugin doesn't seem to offer anything like that: https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.FindBugs.html

The FindBugs Gradle plugin does seem to track the info, I can't seem to determine if it exposes it or not: https://github.com/gradle/gradle/blob/master/subprojects/code-quality/src/main/groovy/org/gradle/api/plugins/quality/internal/findbugs/FindBugsResult.java (`getBugCount()`)

**Comment by sahilTakiar** [comment]
@ibuenros can you review this? Pretty minor change.

**Comment by ibuenros** [comment]
LGTM

**Pull request merged**
