### PR TITLE
Moved AbstractJobLauncher.postProcessTaskStates to before commit

### PR DESCRIPTION
**Pull request by liyinan926**
Signed-off-by: Yinan Li <liyinan926@gmail.com>

### CODE REVIEW

**Comment by liyinan926** [comment]
@zliu41 can you review?

**Comment by zliu41** [comment]
Why put it before job commit? This was intended to be invoked after job committed successfully, e.g., publish job level metrics. If a job fails to commit, the metrics shouldn't be published

**Comment by liyinan926** [comment]
I actually have a use case in Lynda data ingestion: the data publisher needs to know the value of a metric. What's the side effect if the Kafka ingestion job reports metrics in case of commit failure?

**Comment by zliu41** [comment]
In Kafka ingestion, `postProcessTaskStates` will create counters such as number of records pulled. Will these counters be published if the job commit fails? If not then it's fine. It doesn't make sense to publish the counter if the job actually didn't commit those records.

**Comment by liyinan926** [comment]
Makes sense. OK, I will try a different approach for the Lynda use case.

**Pull request closed without merging**
