### PR TITLE
Use UTF-8 instead of the default encoding charset encoding

### PR DESCRIPTION
**Pull request by liyinan926**
Signed-off-by: Yinan Li <liyinan926@gmail.com>

### CODE REVIEW

**Comment by sahilTakiar** [comment]
LGTM. Everything we run on should use the UTF-8 as the default encoding right, so this shouldn't really change anything.

**Comment by liyinan926** [comment]
Yes, I looked at the Charset.defaultCharset() method. It seems it will fall back to UTF-8 for our use.

**Comment by liyinan926** [comment]
@narasimhareddyv, can you verify that the UTF-8 encoding works for the SalesforceExtractor?

**Comment by liyinan926** [comment]
Hey, @narasimhareddyv, can you verify that the UTF-8 encoding works for the SalesforceExtractor?

**Pull request merged**
