### PR TITLE
Fixed hanging embedded Gobblin when initialization fails and metrics.

### PR DESCRIPTION
**Pull request by ibuenros**

### CODE REVIEW

**Comment by ibuenros** [comment]
@abti can you review? Thanks!

**Comment by abti** [comment]
Please check both default run group tests are failing: https://travis-ci.org/linkedin/gobblin/builds/219388176

**Comment by eogren** [comment]
I don't know if you were looking at the same thing, but I noticed EmbeddedDistCp was hanging for me (I was running via the CLI). 

The one-line fix I had was to put a `super.close()` call inside `FileAwareInputStreamDataWriter.close()` -- `InstrumentedDataWriterBase` starts a metrics thread which never gets closed. I don't know why this doesn't break on MR, YARN though. Also not sure if that metrics thread should just be started as a daemon thread so it can't hang the process if not cleaned up properly.

**Comment by ibuenros** [comment]
@eogren No, this is a different case of hanging. Is the one you mentioned fix as well?

**Comment by eogren** [comment]
not yet! see #1757

**Pull request merged**
