### PR TITLE
Fix for #734

### PR DESCRIPTION
**Pull request by kadaan**

### CODE REVIEW

**Comment by liyinan926** [comment]
LGTM.

**Comment by sahilTakiar** [comment]
I think you can also delete `this.jobContext.getJobState().setEndTime(workflowContext.getFinishTime());` since it is set again later on: https://github.com/linkedin/gobblin/blob/8fb95bfe27e67cdcdd84ec41d79d2e84b719cb18/gobblin-runtime/src/main/java/gobblin/runtime/AbstractJobLauncher.java#L311

**Comment by kadaan** [comment]
@sahilTakiar Deleted `this.jobContext.getJobState().setEndTime(workflowContext.getFinishTime())`

**Comment by kadaan** [comment]
@sahilTakiar Updated

**Comment by sahilTakiar** [comment]
LGTM

**Pull request merged**
