### PR TITLE
Added the predicate check to skip full table diff if the existing table's registration time > source table's mod time

### PR DESCRIPTION
**Pull request by tuGithub**

### CODE REVIEW

**Comment by tuGithub** [comment]
@chavdar , please review when you have time.

**Comment by tuGithub** [comment]
@ydai1124 , please review it when you have time

**Comment by tuGithub** [comment]
@ibuenros , please review it when you have time

**Comment by ibuenros** [comment]
It looks good in general. Only comment is: the logic for the table fast skip predicate is almost identical to the partition skip predicate, is there any way to avoid the code repetition? Could we use a single configuration key and instance variable for both?

**Comment by ibuenros** [comment]
Discussed offline, LGTM

**Pull request merged**
