### PR TITLE
Fix Build

### PR DESCRIPTION
**Pull request by zliu41**

### CODE REVIEW

**Comment by sahilTakiar** [comment]
What's the issue with the `gobblin-tunnel` tests? This PR seems to disable a lot of them, which I agree we should do. The whole `gobblin-tunnel` module can probably have its tests disabled. In fact, `gobblin-tunnel` should probably be moved to a separate repo on GitHub.

**Comment by zliu41** [comment]
Not sure, there were assert failures and NPEs. I'm disabling them to unblock Hudson build. We can re-enable them after we know what's wrong with them.

**Comment by chavdar** [comment]
What are the exceptions in gobblin-tunnel?

**Comment by chavdar** [comment]
What is the list of tests that are being disabled?

**Comment by chavdar** [comment]
At least some failures maybe attributable to missing artifacts in the artifactory:

:gobblin-admin:test/export/home/tester/hudson/data/workspace/ETL_infra-gobblin-proxy-build/gobblin-proxy_trunk/gobblin-github/gobblin-core/src/test/java/gobblin/converter/filter/AvroFieldsPickConverterTest.java:38: error: cannot find symbol
      JSONAssert.assertEquals(expected.toString(), converted.toString(), false);
      ^
  symbol:   variable JSONAssert
  location: class AvroFieldsPickConverterTest

**Comment by chavdar** [comment]
Actually, it is a missing testCompile dependency: https://github.com/linkedin/gobblin/pull/1000

**Comment by chavdar** [comment]
There might be also issues due to the new machine that we got. I see error failing to create files.

**Pull request closed without merging**
